baseURL = "https://blog.slucas.fr/"
DefaultContentLanguage = "en"
title = "Technology and Me"
theme = "cocoa-eh"
author = "Sébastien Lucas"
# relativeURLs = true
googleAnalytics = "UA-18757787-1"
disqusShortname = "slucas"
pygmentsCodeFences = true
pygmentsUseClasses=true
rssLimit = 15

[taxonomies]
category = "categories"
series = "series"
tags = "tags"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
copyright = "Copyright © 2018 Sébastien Lucas"
copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/logo.png"
faviconfile = "img/logo.png"
share = true
latestpostcount = 5
github = "seblucas"
email = "sebastien@slucas.fr"
# linkedin = "xxx"
social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
githubRepo = "seblucas/www-blog"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"

[Languages]
[Languages.en]
weight = 1
[Languages.en.params]

[Languages.fr]
weight = 2
[Languages.fr.params]
